### ISSUE TITLE
Zen miner for AMD pointed to hodl

### ISSUE THREAD

**Issue by ne0rrmatrix** [bitsbetrippin/bbtmultiminer#3]
Authentication error for hodl with amd miner
Here is line of code that is wrong:

:zen3
ECHO ZENCoin Claymore - ZENCash to HODLPool - AMD Only
Miners\Claymore_ZCash_AMD_GPU_Miner_v12.6\ZecMiner64.exe -zpool stratum+tcp://mining.hodlpool.com:3032 -zwal %MINER_WEBLOGIN%.%MINER_NAME% -zpsw %WORKER_PASSWORD% -allpools 1
if %ERRORLEVEL% NEQ 0 goto exit
pause

The correct code is

:zen3
ECHO ZENCoin Claymore - ZENCash to HODLPool - AMD Only
Miners\Claymore_ZCash_AMD_GPU_Miner_v12.6\ZecMiner64.exe -zpool stratum+tcp://mining.hodlpool.com:3032 -zwal %WALLET_ADDRESS%.%MINER_NAME% -zpsw %WORKER_PASSWORD% -allpools 1
if %ERRORLEVEL% NEQ 0 goto exit
pause

You need to substitute %MINER_WEBLOGIN% With %WALLET_ADDRESS%

**Comment by bitsbetrippin** [comment]
Commit fix for this, has been merged to master.
